// ============================================================
// GITA GYAN — EXPANDED VERSE DATABASE
// Scenarios, Multi-Commentary, Practical Life Application
// ============================================================

const COMMENTARIES = {
  adiShankaracharya: 'Adi Shankaracharya',
  swamiVivekananda: 'Swami Vivekananda',
  iskcon: 'ISKCON (Prabhupada)',
  chinmayananda: 'Swami Chinmayananda',
  sivananda: 'Swami Sivananda',
};

// Key verses with expanded metadata for scenario-based guidance
const VERSE_SCENARIOS = {
  // ─── STRESS & ANXIETY ───
  '2.47': {
    scenarios: ['stress', 'anxiety', 'overthinking', 'worry', 'pressure', 'burnout'],
    lifeArea: 'Mental Health',
    practicalAdvice: 'Focus on your effort, not the outcome. Do your best and let go of results.',
    modernApplication: 'When overwhelmed at work, focus on the task at hand rather than worrying about promotions or results.',
    commentary: {
      adiShankaracharya: 'You have a right to perform your prescribed duty, but you are not entitled to the fruits of action.',
      swamiVivekananda: 'The secret of work is renunciation. Work for work\'s sake.',
      iskcon: 'You have the right to work, but never to the fruit of work. Work never done for selfish results is far superior.',
      chinmayananda: 'Righteous action is the only thing in your hands. The results are beyond your control.',
      sivananda: 'Do your duty to the best of your ability without attachment to results.',
    },
  },
  '6.35': {
    scenarios: ['stress', 'mind_control', 'restless', 'meditation', 'focus'],
    lifeArea: 'Mental Health',
    practicalAdvice: 'Practice meditation regularly. The mind can be controlled through consistent practice and detachment.',
    modernApplication: 'Start with 10 minutes of daily meditation. Use apps, but the real practice is sitting with your thoughts.',
    commentary: {
      adiShankaracharya: 'Undoubtedly, O mighty-armed one, the mind is difficult to restrain and turbulent, but it can be controlled by practice and detachment.',
      swamiVivekananda: 'The mind is like a restless horse, but through practice it can be tamed.',
      iskcon: 'For one whose mind is uncontrolled, the practice is difficult. But for one whose mind is controlled, it is possible through suitable practice.',
      chinmayananda: 'The mind can be trained and controlled through persistent practice and dispassion.',
      sivananda: 'Through constant practice and non-attachment, the mind can be controlled.',
    },
  },
  // ─── ANGER ───
  '2.62': {
    scenarios: ['anger', 'rage', 'frustration', 'irritation', 'temper'],
    lifeArea: 'Emotional Control',
    practicalAdvice: 'Anger destroys reason. When you feel angry, pause and breathe before reacting.',
    modernApplication: 'Count to 10 before responding. Anger clouds judgment — take a walk, then decide.',
    commentary: {
      adiShankaracharya: 'While contemplating sense objects, attachment develops. From attachment, desire is born. From desire, anger arises.',
      swamiVivekananda: 'Anger is the greatest sin. It destroys everything it touches.',
      iskcon: 'From anger comes delusion; from delusion, loss of memory; from loss of memory, destruction of intelligence.',
      chinmayananda: 'Anger is the product of unfulfilled desires and is the greatest destroyer of peace.',
      sivananda: 'Anger is a great enemy of peace. Control it by patience and forgiveness.',
    },
  },
  '2.63': {
    scenarios: ['anger', 'destruction', 'confusion', 'wrong_decisions'],
    lifeArea: 'Emotional Control',
    practicalAdvice: 'When angry, you lose the ability to think clearly. Never make decisions when angry.',
    modernApplication: 'Important emails, messages, or decisions — wait 24 hours if you\'re angry.',
    commentary: {
      adiShankaracharya: 'Anger leads to delusion; delusion leads to confusion of memory; confusion destroys the intellect.',
      swamiVivekananda: 'When anger enters, reason flees. The wise one waits.',
      iskcon: 'From anger comes complete delusion, and from delusion the bewilderment of memory. When memory is bewildered, intelligence is lost.',
      chinmayananda: 'The chain from desire to destruction is inevitable if one does not practice self-control.',
      sivananda: 'Anger clouds the intellect. The wise remain calm.',
    },
  },
  // ─── FEAR & COURAGE ───
  '2.48': {
    scenarios: ['fear', 'courage', 'bravery', 'confidence', 'doubt'],
    lifeArea: 'Self-Confidence',
    practicalAdvice: 'Be steady in yoga (balance). Success and failure are the same for the balanced mind.',
    modernApplication: 'Face interviews, presentations, and challenges with equanimity. Prepare well, perform without fear.',
    commentary: {
      adiShankaracharya: 'Perform actions established in yoga, having abandoned attachment. Remain even-minded in success and failure.',
      swamiVivekananda: 'Be calm, serene, and steady. That is the secret of success.',
      iskcon: 'Be steadfast in yoga, O Arjuna. Perform your actions without attachment, remaining even-minded in success and failure.',
      chinmayananda: 'Equanimity in pleasure and pain is the hallmark of the established yogi.',
      sivananda: 'Act without attachment. Treat success and failure alike.',
    },
  },
  '18.78': {
    scenarios: ['fear', 'courage', 'faith', 'divine_guidance', 'hope'],
    lifeArea: 'Spiritual Growth',
    practicalAdvice: 'Where Krishna is, there is victory. Have faith that the divine guides those who surrender.',
    modernApplication: 'When facing impossible situations, trust your preparation and let go of fear. The universe conspires.',
    commentary: {
      adiShankaracharya: 'Wherever there is Krishna, the master of yoga, and wherever there is Arjuna, the supreme archer, there will be fortune, victory, and prosperity.',
      swamiVivekananda: 'Wherever there is Krishna, there is success and glory.',
      iskcon: 'Wherever there is Krishna, the master of all mystics, and wherever there is Arjuna, the supreme archer, there will certainly be opulence, victory, and peace.',
      chinmayananda: 'Where there is God and a devoted soul, there is everything that is good.',
      sivananda: 'Wherever there is the Lord of Yoga and the ideal devotee, there is prosperity and righteousness.',
    },
  },
  // ─── RELATIONSHIPS ───
  '5.18': {
    scenarios: ['relationships', 'equality', 'respect', 'judgment', 'prejudice'],
    lifeArea: 'Relationships',
    practicalAdvice: 'See the divine in everyone. Treat all beings with equal respect regardless of their status.',
    modernApplication: 'Treat your janitor and CEO with the same respect. Every person carries the divine spark.',
    commentary: {
      adiShankaracharya: 'The wise see with equal vision a learned Brahmin, a cow, an elephant, a dog, and an outcaste.',
      swamiVivekananda: 'In the sight of the wise, all beings are equal.',
      iskcon: 'The humble sages see the true equality of all living entities and thus engage in devotional service.',
      chinmayananda: 'The enlightened one perceives the same divinity in all beings.',
      sivananda: 'The wise see God in all beings and treat all with equal love.',
    },
  },
  // ─── KARMA & ACTION ───
  '3.19': {
    scenarios: ['karma', 'purpose', 'meaning', 'spiritual_growth', 'detachment'],
    lifeArea: 'Life Purpose',
    practicalAdvice: 'Act without attachment to results. This is the path to liberation.',
    modernApplication: 'Do your job with full dedication, but don\'t let the outcome define your self-worth.',
    commentary: {
      adiShankaracharya: 'Therefore, without attachment, always perform the work that must be done.',
      swamiVivekananda: 'Work is the only way to spiritual liberation.',
      iskcon: 'Therefore, without attachment, always perform the work that must be done, for by performing work without attachment one attains the Supreme.',
      chinmayananda: 'Selfless action performed without attachment leads to God-realization.',
      sivananda: 'Work without attachment is the secret of liberation.',
    },
  },
  // ─── DECISION MAKING ───
  '18.78': {
    scenarios: ['decision', 'career', 'life_choice', 'crossroads', 'uncertainty'],
    lifeArea: 'Decision Making',
    practicalAdvice: 'When confused, align your choices with dharma (duty/righteousness).',
    modernApplication: 'Ask: Does this align with my values? Will it harm others? Is it my duty?',
    commentary: {
      adiShankaracharya: 'Where there is Krishna and Arjuna, there will be victory and prosperity.',
      swamiVivekananda: 'Trust in the divine. Do your duty. The rest will follow.',
      iskcon: 'Wherever there is Krishna, the master of yoga, and wherever there is Arjuna, there will be fortune, victory, and prosperity.',
      chinmayananda: 'When you act with God consciousness, success is assured.',
      sivananda: 'Let God be your guide in all decisions.',
    },
  },
  // ─── FAILURE & RESILIENCE ───
  '2.14': {
    scenarios: ['failure', 'setback', 'loss', 'grief', 'sadness', 'disappointment'],
    lifeArea: 'Resilience',
    practicalAdvice: 'Pleasure and pain come and go like seasons. Be patient. They are temporary.',
    modernApplication: 'A job loss, breakup, or failure is painful but temporary. This too shall pass.',
    commentary: {
      adiShankaracharya: 'The contacts of the senses with their objects produce cold and heat, pleasure and pain. They come and go; they are impermanent.',
      swamiVivekananda: 'Pain and pleasure come and go. They are not permanent. Be steady.',
      iskcon: 'The contacts between the senses and sense objects give rise to cold and heat, pleasure and pain. They are temporary and come and go.',
      chinmayananda: 'Sensory experiences are fleeting. Do not let them disturb your inner peace.',
      sivananda: 'Joy and sorrow are temporary. The wise remain unaffected.',
    },
  },
  // ─── LEADERSHIP ───
  '2.33': {
    scenarios: ['leadership', 'responsibility', 'duty', 'inspiration', 'motivation'],
    lifeArea: 'Leadership',
    practicalAdvice: 'A true leader acts from duty, not desire. Inspire others by example.',
    modernApplication: 'Lead from the front. Take responsibility. Your team mirrors your energy.',
    commentary: {
      adiShankaracharya: 'If you do not fight this righteous battle, you will fail in your duty and lose your reputation.',
      swamiVivekananda: 'The greatest leaders are those who serve others.',
      iskcon: 'If you do not perform this righteous war, you will fail in your duty and incur sin.',
      chinmayananda: 'Shirk not your duty. Face challenges with courage.',
      sivananda: 'A leader must be brave and selfless.',
    },
  },
  // ─── DISCIPLINE ───
  '6.5': {
    scenarios: ['discipline', 'self_control', 'habits', 'procrastination', 'routine'],
    lifeArea: 'Self-Discipline',
    practicalAdvice: 'Your mind can be your best friend or worst enemy. Train it through discipline.',
    modernApplication: 'Build habits. Wake up early. Exercise. Read. Discipline is the bridge between goals and achievement.',
    commentary: {
      adiShankaracharya: 'Let a person lift themselves by their own efforts; let them not degrade themselves. For the self is the friend of the self, and the self is the enemy.',
      swamiVivekananda: 'You are your own friend and your own enemy.',
      iskcon: 'One must elevate oneself by one\'s own mind, not degrade oneself. The mind is the friend of the conditioned soul, and its enemy.',
      chinmayananda: 'The disciplined mind is your greatest asset. The undisciplined mind is your greatest liability.',
      sivananda: 'Conquer the mind by the mind. The mind can be your saviour or destroyer.',
    },
  },
  // ─── DEATH & MORTALITY ───
  '2.20': {
    scenarios: ['death', 'mortality', 'grief', 'loss', 'philosophy'],
    lifeArea: 'Spiritual Growth',
    practicalAdvice: 'The soul is eternal. It is never born and never dies. Understanding this removes fear of death.',
    modernApplication: 'When you lose someone, remember their soul lives on. Grieve, but know death is not the end.',
    commentary: {
      adiShankaracharya: 'The soul is never born, nor does it ever die. It is not slain when the body is slain.',
      swamiVivekananda: 'The soul is immortal. Death is but a change of scene.',
      iskcon: 'For the soul there is neither birth nor death. It is not slain when the body is slain.',
      chinmayananda: 'The Atman is eternal, changeless, and beyond birth and death.',
      sivananda: 'The Self is never born and never dies. It is eternal.',
    },
  },
  // ─── LOVE & COMPASSION ───
  '12.13': {
    scenarios: ['love', 'compassion', 'kindness', 'hatred', 'enmity'],
    lifeArea: 'Relationships',
    practicalAdvice: 'Be friendly to all, compassionate, and egoless. This is the sign of a true devotee.',
    modernApplication: 'Practice radical kindness. Forgive those who hurt you. Compassion heals both giver and receiver.',
    commentary: {
      adiShankaracharya: 'He who is free from enmity towards all beings, friendly and compassionate, free from ego — he is dear to Me.',
      swamiVivekananda: 'He who sees the Lord in all beings, who is free from hatred — he is dear to God.',
      iskcon: 'He who has no enmity towards any being, who is friendly and compassionate, free from ego — such a devotee is dear to Me.',
      chinmayananda: 'The devotee who sees God in all beings and is free from hatred is beloved of the Lord.',
      sivananda: 'He who is devoid of hatred, who is compassionate and egoless — he is dear to God.',
    },
  },
  // ─── SUCCESS ───
  '18.45': {
    scenarios: ['success', 'achievement', 'excellence', 'mastery', 'dedication'],
    lifeArea: 'Career & Success',
    practicalAdvice: 'Dedicate your work as an offering to the divine. Excellence follows devotion.',
    modernApplication: 'Work with full dedication as if you\'re serving God. Success becomes inevitable.',
    commentary: {
      adiShankaracharya: 'By dedicating one\'s own innate duty to the Lord, man attains perfection.',
      swamiVivekananda: 'Work is worship. Dedicate everything to God.',
      iskcon: 'By dedicating their own work to the Supreme Lord, one attains perfection.',
      chinmayananda: 'When action becomes worship, perfection is achieved.',
      sivananda: 'Dedicate all actions to God. This is the secret of success.',
    },
  },
};

// Searchable topics with associated verse references
const TOPIC_VERSES = {
  'stress': ['2.47', '2.48', '6.35', '2.14'],
  'anxiety': ['2.47', '6.35', '18.78'],
  'anger': ['2.62', '2.63'],
  'fear': ['2.48', '18.78', '2.20'],
  'courage': ['2.48', '18.78'],
  'karma': ['3.19', '2.47'],
  'dharma': ['3.19', '18.78'],
  'relationships': ['5.18', '12.13'],
  'love': ['12.13'],
  'success': ['18.45', '2.47'],
  'failure': ['2.14', '2.48'],
  'decision': ['18.78', '2.47'],
  'discipline': ['6.5'],
  'meditation': ['6.35', '6.5'],
  'death': ['2.20'],
  'grief': ['2.20', '2.14'],
  'leadership': ['2.33'],
  'purpose': ['3.19', '2.47'],
  'peace': ['6.35', '5.18'],
  'wisdom': ['2.20', '2.47', '5.18'],
  'detachment': ['2.47', '3.19'],
  'compassion': ['12.13'],
  'ego': ['12.13', '6.5'],
  'patience': ['2.14', '2.62'],
  'confidence': ['2.48', '6.5'],
  'discipline': ['6.5'],
  'habits': ['6.5'],
  'procrastination': ['6.5'],
  'overthinking': ['2.47', '6.35'],
  'worry': ['2.47', '2.14'],
  'burnout': ['2.47', '6.35'],
  'confusion': ['2.63', '6.5'],
  'doubt': ['2.48', '18.78'],
  'revenge': ['2.62', '2.63'],
  'forgiveness': ['2.62', '12.13'],
  'ego': ['12.13', '6.5'],
  'pride': ['12.13'],
  'jealousy': ['5.18', '2.62'],
  'greed': ['2.62', '3.19'],
  'lust': ['2.62'],
  'attachment': ['2.47', '3.19'],
  'letting go': ['2.14', '2.47'],
  'new beginning': ['2.47', '18.78'],
  'hardship': ['2.14', '2.48'],
  'loss': ['2.20', '2.14'],
  'change': ['2.14', '2.47'],
  'spirituality': ['3.19', '5.18', '12.13'],
  'god': ['18.78', '12.13'],
  'soul': ['2.20'],
  'mind': ['6.5', '6.35'],
  'work': ['2.47', '3.19', '18.45'],
  'job': ['2.47', '18.45'],
  'career': ['2.47', '18.45'],
  'business': ['2.47', '3.19'],
  'money': ['2.47', '18.45'],
  'family': ['5.18', '12.13'],
  'friendship': ['5.18', '12.13'],
  'enemy': ['12.13', '2.62'],
  'peace of mind': ['6.35', '2.14'],
  'happiness': ['2.14', '6.35'],
  'suffering': ['2.14', '2.47'],
  'karma yoga': ['3.19', '2.47'],
  'bhakti yoga': ['12.13', '18.78'],
  'jnana yoga': ['2.20', '5.18'],
  'raja yoga': ['6.35', '6.5'],
};

// Daily verse rotation
const DAILY_VERSES = [
  { chapter: 2, verse: 47 },
  { chapter: 2, verse: 48 },
  { chapter: 2, verse: 14 },
  { chapter: 2, verse: 20 },
  { chapter: 2, verse: 62 },
  { chapter: 3, verse: 19 },
  { chapter: 5, verse: 18 },
  { chapter: 6, verse: 5 },
  { chapter: 6, verse: 35 },
  { chapter: 12, verse: 13 },
  { chapter: 18, verse: 45 },
  { chapter: 18, verse: 78 },
  { chapter: 2, verse: 33 },
  { chapter: 2, verse: 63 },
  { chapter: 2, verse: 48 },
];

// Mood to verse mapping
const MOOD_VERSES = {
  'stressed': ['2.47', '6.35', '2.14'],
  'anxious': ['2.47', '6.35', '18.78'],
  'angry': ['2.62', '2.63'],
  'sad': ['2.14', '2.20', '2.48'],
  'happy': ['12.13', '18.45'],
  'confused': ['6.5', '18.78', '2.47'],
  'lost': ['3.19', '2.47', '18.78'],
  'scared': ['2.48', '18.78', '2.20'],
  'hopeless': ['18.78', '2.20', '2.14'],
  'motivated': ['3.19', '18.45', '2.47'],
  'grateful': ['12.13', '5.18'],
  'lonely': ['2.20', '18.78', '12.13'],
  'guilty': ['2.47', '2.14'],
  'jealous': ['5.18', '2.62'],
  'overwhelmed': ['2.47', '6.35', '6.5'],
  'tired': ['2.47', '2.14'],
  'excited': ['3.19', '18.45'],
  'peaceful': ['6.35', '5.18', '12.13'],
  'lost my job': ['2.47', '2.14', '3.19'],
  'relationship problems': ['5.18', '12.13', '2.62'],
  'career confusion': ['2.47', '18.78', '3.19'],
  'dealing with failure': ['2.14', '2.48', '2.47'],
  'fear of death': ['2.20', '18.78'],
  'meaning of life': ['3.19', '2.20', '2.47'],
  'how to meditate': ['6.35', '6.5'],
  'what is dharma': ['3.19', '18.78'],
  'dealing with loss': ['2.20', '2.14'],
  'need confidence': ['2.48', '6.5', '18.78'],
  'improve discipline': ['6.5', '3.19'],
  'better relationships': ['5.18', '12.13'],
  'overcome fear': ['2.48', '18.78', '2.20'],
  'manage anger': ['2.62', '2.63'],
  'find purpose': ['3.19', '2.47'],
  'letting go': ['2.14', '2.47'],
  'should i quit my job': ['2.47', '3.19', '18.78'],
  'my manager insulted me': ['2.14', '2.62', '2.48'],
  'feeling lost': ['3.19', '2.47', '18.78'],
  'what would krishna advise': ['2.47', '18.78', '3.19'],
};

// Regional language commentary translations (key verses only)
const COMMENTARY_TRANSLATIONS = {
  '2.47': {
    hi: {
      adiShankaracharya: 'आपका कर्तव्य कर्म करने का अधिकार है, लेकिन फल का अधिकार नहीं है।',
      swamiVivekananda: 'कर्म का रहस्य त्याग है। कर्म के लिए ही कर्म करो।',
      iskcon: 'आपके पास कर्म करने का अधिकार है, लेकिन कभी भी फल का नहीं।',
      chinmayananda: 'धार्मिक कर्म ही आपके हाथ में है। फल परमात्मा पर निर्भर हैं।',
      sivananda: 'फल की चिंता किए बिना अपना कर्तव्य पूरी क्षमता से करें।',
    },
    ta: {
      adiShankaracharya: 'உங்களுக்கு கடமையைச் செய்யும் உரிமை உள்ளது, ஆனால் விளைவுகளுக்கு இல்லை.',
      swamiVivekananda: 'வேலையின் ரகசியம் துறவு. வேலைக்காகவே வேலை செய்யுங்கள்.',
      iskcon: 'செயல்படும் உரிமை உங்களுக்கு உள்ளது, ஆனால் பலனுக்கு இல்லை.',
      chinmayananda: 'நீதியான செயல் உங்கள் கையில் உள்ளது. பலன்கள் கடவுளைச் சார்ந்தவை.',
      sivananda: 'பலன் பற்றின்றி உங்கள் கடமையை சிறப்பாகச் செய்யுங்கள்.',
    },
    bn: {
      adiShankaracharya: 'আপনার কর্তব্য পালন করার অধিকার আছে, কিন্তু ফলের অধিকার নেই।',
      swamiVivekananda: 'কর্মের রহস্য ত্যাগ। কর্মের জন্যই কর্ম করুন।',
      iskcon: 'কর্ম করার অধিকার আছে, কিন্তু ফলের অধিকার নেই।',
      chinmayananda: 'ধর্মীয় কর্মই আপনার হাতে। ফল ঈশ্বরের উপর নির্ভরশীল।',
      sivananda: 'ফলের চিন্তা ছাড়া আপনার কর্তব্য সর্বোচ্চ ক্ষমতায় করুন।',
    },
  },
  '18.66': {
    hi: {
      adiShankaracharya: 'सभी धर्मों को त्यागकर मेरे शरण में आओ। मैं तुम्हें सभी पापों से मुक्त कर दूँगा। शोक मत करो।',
      swamiVivekananda: 'सब कुछ छोड़कर मेरे पास आओ। मैं तुम्हें सब पापों से मुक्त करूँगा।',
      iskcon: 'सभी धर्मों को त्यागकर केवल मेरे शरण में आओ। मैं तुम्हें सभी पापों से मुक्त करूँगा। शोक मत करो।',
      chinmayananda: 'सर्व धर्मान् परित्यज्य — सभी बाहरी धार्मिक क्रियाओं को छोड़कर मेरे शरण में आओ।',
      sivananda: 'भगवान की शरण में जाना ही सबसे महान कर्म है।',
    },
    ta: {
      adiShankaracharya: 'அனைத்து கடமைகளையும் விட்டுவிட்டு என் பாதுகாப்பில் வாருங்கள். நான் உங்களை அனைத்து பாவங்களிலிருந்தும் விடுவிக்கிறேன்.',
      swamiVivekananda: 'அனைத்தையும் விட்டுவிட்டு என்னிடம் வாருங்கள். நான் உங்களை விடுவிக்கிறேன்.',
      iskcon: 'அனைத்து கடமைகளையும் துறந்து என் பாதுகாப்பில் வாருங்கள்.',
      chinmayananda: 'வெளிப்புற சடங்குகளை விட்டுவிட்டு என்னை நாடுங்கள்.',
      sivananda: 'இறைவனின் பாதுகாப்பை நாடுவதே மிகப் பெரிய செயல்.',
    },
  },
  '2.48': {
    hi: {
      adiShankaracharya: 'योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय — हे अर्जुन, सिद्धि-असिद्धि में समभाव रखकर कर्म करो।',
      swamiVivekananda: 'सफलता और असफलता में समान रहकर कर्म करो।',
      iskcon: 'सिद्धि और असिद्धि में समान भाव से कर्म करो।',
      chinmayananda: 'योग में स्थित होकर संग त्यागकर कर्म करो।',
      sivananda: 'समभाव रखकर कर्म करो।',
    },
  },
};

export {
  COMMENTARIES,
  VERSE_SCENARIOS,
  TOPIC_VERSES,
  DAILY_VERSES,
  MOOD_VERSES,
  COMMENTARY_TRANSLATIONS,
};
