import React from 'react';
import { useTranslation } from 'react-i18next';

export default function TermsPage({ onBack }) {
  const { t } = useTranslation();

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      {/* Header */}
      <div className="border-b border-white/5 bg-gray-950/80 backdrop-blur-2xl sticky top-0 z-40">
        <div className="max-w-3xl mx-auto flex items-center px-4 py-3">
          <button onClick={onBack} className="mr-3 w-8 h-8 rounded-full bg-white/5 hover:bg-white/10 flex items-center justify-center text-gray-400 hover:text-white transition-all">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M19 12H5M12 19l-7-7 7-7"/></svg>
          </button>
          <h1 className="text-white font-bold text-lg">Terms of Service</h1>
        </div>
      </div>

      <main className="max-w-3xl mx-auto px-4 py-8">
        <div className="prose prose-invert max-w-none space-y-8">
          <div>
            <p className="text-gray-400 text-sm mb-4">Last updated: June 26, 2026</p>
            <p className="text-gray-300 text-sm leading-relaxed">
              Welcome to Gita Gyan. By using our application, you agree to these Terms of Service. Please read them carefully.
            </p>
          </div>

          <section>
            <h2 className="text-white font-bold text-lg mb-3">1. Acceptance of Terms</h2>
            <p className="text-gray-300 text-sm leading-relaxed">
              By accessing or using Gita Gyan, you agree to be bound by these Terms of Service. If you do not agree, please do not use the application.
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-lg mb-3">2. Description of Service</h2>
            <p className="text-gray-300 text-sm leading-relaxed">
              Gita Gyan is an AI-powered spiritual mentor application that provides guidance based on the Bhagavad Gita. It includes chat-based AI conversations, verse exploration, meditation tools, journaling, and progress tracking.
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-lg mb-3">3. AI-Generated Content</h2>
            <div className="space-y-3 text-gray-300 text-sm leading-relaxed">
              <p>AI responses are generated by language models and may not always be accurate, complete, or suitable for your specific situation.</p>
              <p>Gita Gyan is not a substitute for professional medical, psychological, or legal advice.</p>
              <p>If you are experiencing a mental health crisis, please contact a qualified professional or emergency services immediately.</p>
              <p>The AI strives to provide respectful, helpful guidance based on the Bhagavad Gita, but interpretations may vary.</p>
            </div>
          </section>

          <section>
            <h2 className="text-white font-bold text-lg mb-3">4. User Conduct</h2>
            <div className="space-y-3 text-gray-300 text-sm leading-relaxed">
              <p>You agree not to:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li>Use the service for any unlawful purpose</li>
                <li>Attempt to exploit or abuse the AI system</li>
                <li>Impersonate another person</li>
                <li>Attempt to reverse-engineer the service</li>
                <li>Interfere with the proper functioning of the application</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-white font-bold text-lg mb-3">5. Intellectual Property</h2>
            <p className="text-gray-300 text-sm leading-relaxed">
              The Gita Gyan application, including its design, code, and content, is protected by intellectual property laws. The Bhagavad Gita verses are in the public domain. Commentary translations are attributed to their respective authors.
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-lg mb-3">6. Limitation of Liability</h2>
            <p className="text-gray-300 text-sm leading-relaxed">
              Gita Gyan is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service, including but not limited to direct, indirect, incidental, or consequential damages.
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-lg mb-3">7. Termination</h2>
            <p className="text-gray-300 text-sm leading-relaxed">
              We may terminate or suspend your access to the service at any time, without prior notice, for conduct that we determine violates these Terms or is harmful to other users or the service.
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-lg mb-3">8. Changes to Terms</h2>
            <p className="text-gray-300 text-sm leading-relaxed">
              We reserve the right to modify these Terms at any time. We will notify you of material changes by posting the updated Terms on this page. Your continued use of the service after changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-white font-bold text-lg mb-3">9. Contact</h2>
            <p className="text-gray-300 text-sm leading-relaxed">
              For questions about these Terms, please contact{' '}
              <a href="mailto:legal@gitagyan.app" className="text-amber-400 hover:text-amber-300 transition-colors">legal@gitagyan.app</a>.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
